name: Maven Build and Test
# on: [push, pull_request, workflow_dispatch]
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: icdemo/hello-action@c9cbdf8361071a302d0892e3ea311cad00517f4d
        with:
          who-to-greet: 'Action Maintainer'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package
      - name: Test with Maven
        run: mvn -B test
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports
            target/site
      - name: Show test failures
        shell: bash
        run: |
          ./script.sh
      - id: hello-composite
        uses: icdemo/hello-action-composite@6f838b5802bc076cd5c6eb319bbcdc83d26a657b
        with:
          who-to-greet: 'Cardano the doctor and mathematician'
          target-path: target/surefire-reports
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: iclimdocker/hello
          tags: |
            type=sha,format=short,prefix=
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            iclimdocker/hello:latest
            ${{ steps.meta.outputs.tags }}
  integration:
    needs: deploy
    runs-on: ubuntu-latest
    container: maven:3.9.9-amazoncorretto-17
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      hello:
        credentials:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        image: iclimdocker/hello
        options: >-
          --health-cmd "curl -f http://hello:8080/ping"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 30s
    steps:
      - name: Run Test Service
        run: |
          curl --location 'http://hello:8080/api/v1/say/luigi/abc'
          curl --location 'http://hello:8080/api/v1/say/mario/xyz'
          curl --location 'http://hello:8080/api/v1/get/mario'
          curl --location 'http://hello:8080/api/v1/get/luigi'
